POST http://localhost:8000/api/v1/auth/login/ HTTP/1.1
Content-Type: application/json
  
{
    "login": "test1",
    "password": "1234567890"
}




###


POST  http://localhost:8000/api/v1/auth/create/user/ HTTP/1.1
Content-Type: application/json


{
    "email": "test6@mail.com", 
    "username": "test6" , 
    "password": "1234567890", 
    "role": "teamlead",
    "joined_date": "2024-01-01"
}

###

POST http://localhost:8000/api/v1/auth/token/refresh/ HTTP/1.1
Content-Type: application/json



###


POST http://localhost:8000/api/v1/auth/logout/ HTTP/1.1
Content-Type: application/json




###

POST http://localhost:8000/api/v1/auth/otp/send/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MzQwMjkxLCJpYXQiOjE3NzgzMzg0OTEsImp0aSI6ImRkZmU4ZTA1MTgwYjQ4MzZhMjgzYzQ5N2JiMzgxNTlmIiwidXNlcl9pZCI6IjEifQ.J-QYmmr-bg5gMOAk7krhIhqqcLEZVfMVemwT1sR_buQ

{
    "email": "test@mail.com",
    "purpose": "PASSWORD_RESET"
}




###

POST http://localhost:8000/api/v1/auth/otp/verify/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MzQwMjkxLCJpYXQiOjE3NzgzMzg0OTEsImp0aSI6ImRkZmU4ZTA1MTgwYjQ4MzZhMjgzYzQ5N2JiMzgxNTlmIiwidXNlcl9pZCI6IjEifQ.J-QYmmr-bg5gMOAk7krhIhqqcLEZVfMVemwT1sR_buQ

{
    "otp": 667613,
    "email": "test@mail.com",
    "purpose": "PASSWORD_RESET"
}




###

POST http://localhost:8000/api/v1/auth/password/reset/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4MzIwNTczLCJpYXQiOjE3NzgzMTg3NzMsImp0aSI6IjNhMTVhMmJmOWIzOTQ4MGE4YzBjYzE5MWMxMDEyODE3IiwidXNlcl9pZCI6IjEifQ.Pt2-7YdYG7B6-OPDHIerRdbpr0wOmii5Slh753KhUXQ


{
  "new_password": "1234567890",
  "reset_token": "uHuHT4hpJHrSB-8AgHjiZK7rus41CAtwiyIUPG_xgbA"
}



### 

GET  http://localhost:8000/api/v1/users/me/ HTTP/1.1
Content-Type: application/json


###


PATCH   http://localhost:8000/api/v1/users/me/ HTTP/1.1
Content-Type: application/json



{
    "full_name": "Admin",
    "phone": "66975657657",
    "gender": "MALE"
}



### 

PATCH http://localhost:8000/api/v1/users/019e0bc5-e798-7b32-a214-09c9af25a32a/status/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc4NTg4OTA0LCJpYXQiOjE3Nzg1ODcxMDQsImp0aSI6IjJiOGM4NTk2YmU4NjQ4ZGRiYmVhZTA2NjcyN2E0YzU3IiwidXNlcl9pZCI6IjEifQ.xmYsBOaqez5m-xJq6S4Xi_FTxyEIdExFq4T3xllPVaQ


{
    "new_status": "ACTIVE",
    "suspension_reason": "Testing",
    "suspension_start": "2025-02-12",
    "suspension_end": "2026-02-12"
}