# Generated by Django 6.0.4 on 2026-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='logout_time',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGGED_OUT', 'Logged Out'), ('SESSION_EXPIRED', 'Session Expired'), ('LOCKED', 'Account Locked')], default=False, max_length=30),
            preserve_default=False,
        ),
    ]
