# Generated by Django 6.0.4 on 2026-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_loginhistory_login_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='is_used',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('INVALIDATED', 'Invalidated'), ('MAX_ATTEMPTS_EXCEEDED', 'Max Attempts Exceeded')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGGED_OUT', 'Logged Out'), ('SESSION_EXPIRED', 'Session Expired'), ('ACCOUNT_LOCKED', 'Account Locked')], max_length=30),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('LOGIN', 'Login'), ('VERIFY_EMAIL', 'Verify Email')], max_length=50),
        ),
    ]
