# Generated by Django 6.0.4 on 2026-05-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_otpverification_is_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatushistory',
            old_name='changed_user',
            new_name='changed_by',
        ),
    ]
