# Generated by Django 6.0.4 on 2026-05-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_joined_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_at',
            new_name='joined_date',
        ),
    ]
