# Generated by Django 6.0.4 on 2026-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_joined_at_user_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='token_identifier',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
