# Generated by Django 6.0.4 on 2026-05-16 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_otpverification_token_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='token_identifier',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
